
services:
#######################################

# User-Service containers
#######################################

  user-service.dev:
    build: ./user-service
    container_name: user-service
    ports:
      - "8083:80"
    networks:
      - web

  user-postgres.dev:
    image: postgres:16.3-alpine
    container_name: user-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    networks:
      - web

  kafka-user-service.dev:
    image: apache/kafka:3.9.0
    container_name: kafka-user-service
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://localhost:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-user-service.dev:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 1
    networks:
      - web

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8085:8080"
    depends_on:
      - kafka-user-service.dev
    environment:
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-user-service.dev:9092
      DYNAMIC_CONFIG_ENABLED: 'true'
    networks:
      - web

#Containers connected to the same bridge network can communicate with each other
networks:
  web:
    driver: bridge