
services:
  consul.dev:
    container_name: consul-service
    image: hashicorp/consul:1.20
    ports:
      - "8500:8500" # Consul UI
    networks:
      - web
    restart: always
  
  ## Gateway Service Containers
  #########################################
  gateway-service.dev:
    build: ./gateway-service
    container_name: gateway-service
    ports:
      - "80:80"
    depends_on:
      - consul.dev
    networks:
      - web

# #######################################
# ## User-Service containers
# #######################################

  user-service.dev:
    build: ./user-service
    container_name: user-service
    depends_on:
      - consul.dev
      - user-postgres.dev
    networks:
      - web

  user-postgres.dev:
    image: postgres:16.3-alpine
    container_name: user-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes: 
      - ./project-db/user-postgres/postgres/:/var/lib/postgresql/data/
    networks:
      - web

  kafka-user-service.dev:
    image: apache/kafka:3.9.0
    container_name: kafka-user-service
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://localhost:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-user-service.dev:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 1
    networks:
      - web

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8085:8080"
    depends_on:
      - kafka-user-service.dev
    environment:
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-user-service.dev:9092
      DYNAMIC_CONFIG_ENABLED: 'true'
    networks:
      - web
    
  ###############################
  # Product-Service containers
  #############################
  product-service.dev:
    build: ./product-service
    container_name: product-service
    depends_on:
      - consul.dev
      - product-postgres.dev
    # ports:
    #   - "8086:80"
    networks:
      - web

  # Product Postgres containers
  ###############################
  product-postgres.dev:
    image: postgres:16.3-alpine
    container_name: product-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5434:5432"
    volumes: 
      - ./project-db/product-postgres/postgres/:/var/lib/postgresql/data/
    networks:
      - web

  
  ##############################
  # Cart-Service containers
  ############################
  cart-service.dev:
    build: ./cart-service
    container_name: cart-service
    depends_on:
      - consul.dev
      - cart-postgres.dev
    # ports:
    #   - "8085:80"
    networks:
      - web

  # Product Postgres containers
  ##############################
  cart-postgres.dev:
    image: postgres:16.3-alpine
    container_name: cart-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5435:5432"
    volumes: 
      - ./project-db/cart-postgres/postgres/:/var/lib/postgresql/data/
    networks:
      - web
  
  #######################################
  # Order Service Containers
  #######################################

  order-service.dev:
    build: ./order-service
    container_name: order-service
    depends_on:
      - consul.dev
      - order-postgres.dev
    networks:
      - web

  order-postgres.dev:
    image: postgres:16.3-alpine
    container_name: order-postgres.dev
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5436:5432"
    networks:
      - web

  kafka-order-service.dev:
    image: apache/kafka:3.9.0
    container_name: kafka-order-service
    ports:
      - "9093:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://localhost:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-order-service:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 1
    networks:
      - web

  kafka-order-ui:
      container_name: kafka-order-ui
      image: provectuslabs/kafka-ui:latest
      ports:
        - "8086:8080"
      depends_on:
        - kafka-order-service.dev
      environment:
        KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-order-service.dev:9092
        DYNAMIC_CONFIG_ENABLED: 'true'
      networks:
        - web
#Containers connected to the same bridge network can communicate with each other
networks:
  web:
    driver: bridge